image: node:11

# cache:
#   paths:
#     - node_modules/

stages:
  - test
  - deploy

test_all:
  stage: test
  script:
    - yarn
    - yarn test
npm_latest:
  stage: deploy
  script:
    - echo "publish npm latest"
    - yarn
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - node tools/build publish latest
  environment:
    name: npm
    url: https://www.npmjs.com/package/effector
  # when: manual
  only:
    - master
npm_next:
  stage: deploy
  script:
    - echo "publish npm next"
    - yarn
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - node tools/build publish next
  environment:
    name: npm
    url: https://www.npmjs.com/package/effector
  when: manual
  only:
    - master
npm_canary:
  stage: deploy
  script:
    - yarn
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - yarn build
    - VERSION_HASH=${CI_COMMIT_SHA:0:8} node tools/versionHash
    - cd npm/effector && npm publish
  environment:
    name: npm_canary
    url: https://www.npmjs.com/package/@effector/canary
  only:
    - master
