name: effector release candidate publish

on:
  push:
    branches:
      - release/v23
    paths:
      - 'packages/*/package.json'
      - 'packages/*/*/package.json'
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node-16-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install deps
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: set npm config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN && npm config set //npm.pkg.github.com/:_authToken $GITHUB_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: publish packages
        run: node tools/build publish next
        env:
          PRINT_ERRORS: false
  trigger_changelog_generator:
    runs-on: ubuntu-latest
    needs: [publish-npm]
    steps:
      - uses: actions/checkout@v4
      - name: Run pipeline for changelog generation
        run: curl -X POST -d {} "$AMPLIFY_CHANGELOG_WEBHOOK" -H "Content-Type:application/json"
        env:
          AMPLIFY_CHANGELOG_WEBHOOK: ${{ secrets.amplify_changelog_webhook }}
